config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "requests#index"
  resources :requests do
    resources :applies, only: [:new, :create]
    resources :supports, only: [:index, :new, :create]
  end
  resources :users, only: :show
end

app/models/apply.rb
class Apply < ApplicationRecord

  belongs_to :user
  belongs_to :request

  validates :reason, presence: true
  validates :phone_num, format: { with: /\A\d{10}$|^\d{11}\z/, message: :invalid_phone_num }, allow_blank: true
  validates :user_id, uniqueness: { scope: :request_id }
end

app/controllers/applies_controller.rb
class AppliesController < ApplicationController

  def new
    @apply = Apply.new
  end

  def create
    @apply = Apply.new(apply_params)
    if @apply.save
      redirect_to request_path(@apply.request)
    else
      render :new
    end
  end

  private
  def apply_params
    params.permit(:phone_num, :reason, :question).merge(user_id: current_user.id, request_id: params[:request_id])
  end

end

app/helpers/applies_helper.rb
module AppliesHelper
end

app/views/applies/new.html.erb
<link href="https://fonts.googleapis.com/css2?family=M+PLUS+1p:wght@800&display=swap" rel="stylesheet">

<%= render "shared/apply_header" %>

<div class='apply-main'>
  <div class="form-group new-form">
    <%= form_with url: request_applies_path, class: 'new-request', local: true do |f| %>
      <%= render "shared/error_messages", model: @apply %>

      <div class="new-input">
        <div class="new-title">
          <%= f.label :"ご連絡先(電話番号)" %><br />
          <%= f.text_field :phone_num, autofocus: true, autocomplete: "phone_num", placeholder:"電話でのご連絡をご希望の方のみ", class: "form-control  tel-form" %>
        </div>

        <div class="new-content">
          <%= f.label :"応募理由・動機" %><br />
          <%= f.text_area :reason, autofocus: true, autocomplete: "reason", placeholder:"必須項目", class: "form-control reason-form" %>
        </div>

        <div class="new-job">
          <%= f.label :"依頼に対する質問やご不明点等" %><br />
          <%= f.text_area :question, autofocus: true, autocomplete: "question", placeholder:"もしあればご入力ください", class: "form-control question-form" %>
        </div>

        <div class="request-submit">
          <%= f.submit "応募する", class: "btn btn-primary request-button" %>
        </div>
      </div>

    <% end %>
  </div>
</div>

<%= render "shared/footer" %>