config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "requests#index"
  resources :requests do
    resources :applies, only: [:new, :create]
    resources :supports, only: [:index, :new, :create]
  end
  resources :users, only: :show
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  has_many :applies
  has_many :supports
  has_one_attached :image

  with_options presence: true do
    validates :title, length: { maximum: 10 }
    validates :image
    validates :category_id, numericality: { other_than: 1, message: :invalid_id }
    validates :content
    validates :job
    validates :want
    validates :prefecture_id, numericality: { other_than: 0, message: :invalid_id }
    validates :city
    validates :reword
    validates :period
    validates :people, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 999 }
    validates :donation, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 9999999 }
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
  belongs_to :category
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :move_to_index, only: [:edit, :update, :destroy]
  before_action :period_block, only: [:edit, :update]

  def index
    @requests = Request.order('created_at DESC')
    @today = Date.today
  end

  def new
    @request = Request.new
  end

  def create
    @request = Request.new(request_params)
    if @request.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @request = Request.find(params[:id])
    @today = Date.today
    @donation = @request.supports.sum(:price)
  end

  def edit
  end

  def update
    if @request.update(request_params)
      redirect_to request_path
    else
      render :edit
    end
  end

  def destroy
    if @request.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  private
  def request_params
    params.require(:request).permit(:title, :category_id, :content, :url, :job, :want, :period, :reword, :prefecture_id, :city, :people, :donation, :image).merge(user_id: current_user.id)
  end

  def move_to_index
    @request = Request.find(params[:id])
    unless @request.user == current_user
      redirect_to action: :index
    end
  end

  def period_block
    @today = Date.today
    if @today == @request.period.tomorrow
      redirect_to action: :index
    end
  end

end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/edit.html.erb
<link href="https://fonts.googleapis.com/css2?family=M+PLUS+1p:wght@800&display=swap" rel="stylesheet">

<%= render "shared/show_header" %>

<div class='new-main'>
  <div class="form-group new-form">
    <%= form_with model: @request, class: 'new-request', local: true do |f| %>
      <%= render "shared/error_messages", model: f.object %>

      <div class="new-input">
        <div class="new-title">
          <%= f.label :"タイトル" %><br />
          <%= f.text_field :title, autofocus: true, autocomplete: "title", placeholder:"10文字以内", class: "form-control  title-form" %>
        </div>

        <div class="new-image">
          <%= f.label :"画像" %><br />
          <%= f.file_field :image, class:"form-control-file image-form" %>
        </div>

        <div class="new-category">
            <%= f.label :"カテゴリー" %><br />
            <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class: "category-select form-control"}) %>
        </div>

        <div class="new-content">
          <%= f.label :"依頼内容" %><br />
          <%= f.text_area :content, autofocus: true, autocomplete: "content", class: "form-control content-form" %>
        </div>

        <div class="new-url">
          <%= f.label :"ホームページ・SNSアカウント等のURL" %><br />
          <%= f.text_field :url, autofocus: true, autocomplete: "url", class: "form-control  url-form" %>
        </div>

        <div class="new-job">
          <%= f.label :"活動内容" %><br />
          <%= f.text_area :job, autofocus: true, autocomplete: "job", class: "form-control job-form" %>
        </div>

        <div class="new-want">
          <%= f.label :"求める人物" %><br />
          <%= f.text_area :want, autofocus: true, autocomplete: "want", placeholder:"ex) ボランティア経験がある・未経験でも興味のある方", class: "form-control want-form" %>
        </div>

        <div class="form-row new-region">
          <div class="col-md-3 new-prefecture">
            <%= f.label :"活動地域" %><br />
            <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class: "prefecture-select form-control"}) %>
          </div>
          <div class="col-md-7 new-city">
            <%= f.label :"活動場所" %><br />
            <%= f.text_field :city, autofocus: true, autocomplete: "city", placeholder:"ex) ○○公園（××市△△123-45）",class: "form-control  city-form" %>
          </div>
        </div>

        <div class="new-reword">
          <%= f.label :"報酬・給与" %><br />
          <%= f.text_area :reword, autofocus: true, autocomplete: "reword", class: "form-control reword-form" %>
        </div>

        <div class="new-period">
          <%= f.label :"募集期限" %><br />
          <%= f.date_field :period, autofocus: true, autocomplete: "period", class: "form-control period-form" %>
        </div>

        <div class="new-people">
          <%= f.label :"募集人数" %><br />
          <%= f.label :"(資金援助のみご希望の場合は0を入力してください)"%><br />
          <%= f.text_field :people, autofocus: true, autocomplete: "people", placeholder:"ex) 100", class: "form-control people-form" %>
        </div>

        <div class="new-donation">
          <%= f.label :"募集金額" %><br />
          <%= f.label :"(資金援助がご不要の場合は0を入力してください)"%><br />
          <%= f.text_field :donation, autofocus: true, autocomplete: "donation", placeholder:"ex) 200000", class: "form-control donation-form" %>
        </div>

        <div class="request-submit">
          <%= f.submit "変更する", class: "btn btn-primary request-button" %>
        </div>
      </div>

    <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/requests/index.html.erb
<link href="https://fonts.googleapis.com/css2?family=M+PLUS+1p:wght@800&display=swap" rel="stylesheet">

<%= render "shared/header" %>

<div class='request-main'>
  <div class="request-index">
    <ul class='request-lists'>
      <% if @requests %>
        <% @requests.each do |request| %>
          <li class='request-list'>
            <%= link_to request_path(request) do %>
              <div class='request-img-content'>
                <%= image_tag 'index_paper_2.png' ,size: '280x300' ,class: "request-content" %>
                <%= image_tag request.image ,size: '200x115' ,class: "request-img" %>

                <% if request.period < @today %>
                  <%= image_tag 'mark_shimekiri.png' ,size: '220x220',class: "time-over-img" %>
                <% end %>

                <span class="request-title">
                  <strong><%= request.title %></strong>
                </span>
                <span class="request-prefecture">
                  <%= request.prefecture.name %>
                </span>
                <span class="request-period">
                  <% if request.period == @today %>
                    <span class="today-period">本日募集終了！！！</span>
                  <% else%>
                    <strong>募集終了: </strong><%= request.period %>
                  <% end %>
                </span>
              </div>
            <% end %>
          </li>
        <% end %>
      <% else %>
        <li class='sample-list'>
          <%= image_tag 'index_paper_2.png' ,size: '280x200' ,class: "request-sample" %>
          <%= image_tag 'IMG_4693.png' ,size: '200x100' ,class: "sea-sample" %>
          <span class="sample-title">
            <strong>海掃除の参加者募集！！</strong>
          </span>
          <span class="sample-prefecture">
            静岡県
          </span>
          <span class="sample-period">
            募集終了: 2021/5/30
          </span>
        </li>
        <li class='sample-list-2'>
          <%= image_tag 'index_paper_2.png' ,size: '280x300' ,class: "request-sample" %>
        </li>
        <li class='sample-list-3'>
          <%= image_tag 'index_paper_2.png' ,size: '280x300' ,class: "request-sample" %>
        </li>
        <li class='sample-list-4'>
          <%= image_tag 'index_paper_2.png' ,size: '280x300' ,class: "request-sample" %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class='request-btn'>
    <a href="/requests/new">
      <span class='request-btn-text'>依頼作成</span>
      <%= image_tag 'cork_board_paper.png' , size: '185x100' ,class: "request-btn-png" %>
    </a>
  </div>

</div>

<%= render "shared/footer" %>

app/views/requests/new.html.erb
<link href="https://fonts.googleapis.com/css2?family=M+PLUS+1p:wght@800&display=swap" rel="stylesheet">

<%= render "shared/new_header" %>

<div class='new-main'>
  <div class="form-group new-form">
    <%= form_with model: @request, class: 'new-request', local: true do |f| %>
      <%= render "shared/error_messages", model: f.object %>

      <div class="new-input">
        <div class="new-title">
          <%= f.label :"タイトル" %><br />
          <%= f.text_field :title, autofocus: true, autocomplete: "title", placeholder:"10文字以内", class: "form-control  title-form" %>
        </div>

        <div class="new-image">
          <%= f.label :"画像" %><br />
          <%= f.file_field :image, class:"form-control-file image-form" %>
        </div>

        <div class="new-category">
            <%= f.label :"カテゴリー" %><br />
            <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class: "category-select form-control"}) %>
        </div>

        <div class="new-content">
          <%= f.label :"依頼内容" %><br />
          <%= f.text_area :content, autofocus: true, autocomplete: "content", class: "form-control content-form" %>
        </div>

        <div class="new-url">
          <%= f.label :"ホームページ・SNSアカウント等のURL" %><br />
          <%= f.text_field :url, autofocus: true, autocomplete: "url", class: "form-control  url-form" %>
        </div>

        <div class="new-job">
          <%= f.label :"活動内容" %><br />
          <%= f.text_area :job, autofocus: true, autocomplete: "job", class: "form-control job-form" %>
        </div>

        <div class="new-want">
          <%= f.label :"求める人物" %><br />
          <%= f.text_area :want, autofocus: true, autocomplete: "want", placeholder:"ex) ボランティア経験がある・未経験でも興味のある方", class: "form-control want-form" %>
        </div>

        <div class="form-row new-region">
          <div class="col-md-3 new-prefecture">
            <%= f.label :"活動地域" %><br />
            <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class: "prefecture-select form-control"}) %>
          </div>
          <div class="col-md-7 new-city">
            <%= f.label :"活動場所" %><br />
            <%= f.text_field :city, autofocus: true, autocomplete: "city", placeholder:"ex) ○○公園（××市△△123-45）",class: "form-control  city-form" %>
          </div>
        </div>

        <div class="new-reword">
          <%= f.label :"報酬・給与" %><br />
          <%= f.text_area :reword, autofocus: true, autocomplete: "reword", class: "form-control reword-form" %>
        </div>

        <div class="new-period">
          <%= f.label :"募集期限" %><br />
          <%= f.date_field :period, autofocus: true, autocomplete: "period", class: "form-control period-form" %>
        </div>

        <div class="new-people">
          <%= f.label :"募集人数" %><br />
          <%= f.label :"(資金援助のみご希望の場合は0を入力してください)"%><br />
          <%= f.text_field :people, autofocus: true, autocomplete: "people", placeholder:"ex) 100", class: "form-control people-form" %>
        </div>

        <div class="new-donation">
          <%= f.label :"募集金額" %><br />
          <%= f.label :"(資金援助がご不要の場合は0を入力してください)"%><br />
          <%= f.text_field :donation, autofocus: true, autocomplete: "donation", placeholder:"ex) 200000", class: "form-control donation-form" %>
        </div>

        <div class="request-submit">
          <%= f.submit "依頼する", class: "btn btn-primary request-button" %>
        </div>
      </div>

    <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/requests/show.html.erb
<link href="https://fonts.googleapis.com/css2?family=M+PLUS+1p:wght@800&display=swap" rel="stylesheet">

<%= render "shared/show_header" %>

<div class="show-request">
  <div class="show-contents">
    <%= image_tag @request.image ,size: '600x350' ,class: "show-img" %>

    <% if @today > @request.period.tomorrow %>
      <%= image_tag 'mark_shimekiri.png' ,size: '470x470' ,class: "end-img" %>
    <% end %>

    <div class="show-title">
      <span class="under"><%= @request.title %></span>
    </div>

    <% if user_signed_in? && @today <= @request.period %>
      <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    <% end %>

    <table class="table table-bordered show-table">
      <tbody>
        <tr>
          <th scope="row"> 依頼者</th>
          <td><%= link_to @request.user.nickname, "/users/#{@request.user.id}", class: "show-nickname" %></td>
        </tr>
        <tr>
          <th scope="row" class="content-name">カテゴリー</th>
          <td><%= @request.category.name %></td>
        </tr>
        <tr>
          <th scope="row">依頼内容</th>
          <td><%= @request.content %></td>
        </tr>
        <tr>
          <th scope="row">URL・SNSアカウント</th>
          <td><%= @request.url %></td>
        </tr>
        <tr>
          <th scope="row">活動内容</th>
          <td><%= @request.job %></td>
        </tr>
        <tr>
          <th scope="row">求める人物</th>
          <td><%= @request.want %></td>
        </tr>
        <tr>
          <th scope="row">募集期間</th>
          <td><%= @request.period %> 〆切</td>
        </tr>
        <tr>
          <th scope="row">報酬・給与</th>
          <td><%= @request.reword %></td>
        </tr>
        <tr>
          <th scope="row">活動場所</th>
          <td><%= @request.prefecture.name %>： <%= @request.city %></td>
        </tr>
        <tr>
          <th scope="row">募集人数</th>
          <td><%= @request.people %>人</td>
        </tr>
        <tr>
          <th scope="row">資金援助目標額</th>
          <td><%= @request.donation.to_s(:delimited, delimiter: ',') %>円</td>
        </tr>
      </tbody>
    </table>

    <div class="show-situation">
      <span class="under">ご依頼への支援状況</span>
      <div class="people-situation">
        <% if @request.people != 0 %>
          <span class="under">応募人数： <%= @request.apply_ids.length %>人</span>
        <% end %>
      </div>
      <div class="donation-situation">
        <% if @request.donation != 0 %>
          <span class="under">支援金総額： <%= @donation.to_s(:delimited, delimiter: ',') %>円</span>
        <% end %>
      </div>
    </div>
  </div>
  <div class="show-button">
    <ul class="show-btn-lists">
      <% if @today > @request.period.tomorrow && @request.user != current_user %>
        <div class="end-message">
          <strong>他のご依頼をご覧ください！！！！</strong>
        </div>
      <% elsif @request.user == current_user && @today > @request.period.tomorrow %>
        <li class="destroy-btn">
          <%= link_to request_path(@request), method: :delete do %>
            <%= image_tag 'book_note_empty.png' , size: '185x100', class: "edit-btn-png" %>
            <span class='destroy-btn-text'>削除する</span>
          <% end %>
        </li>
      <% elsif @request.user == current_user %>
        <li class="edit-btn">
          <%= link_to edit_request_path(@request) do %>
            <%= image_tag 'book_note_empty.png' , size: '185x100', class: "edit-btn-png" %>
            <span class='edit-btn-text'>編集する</span>
          <% end %>
        </li>
        <li class="destroy-btn">
          <%= link_to request_path(@request), method: :delete do %>
            <%= image_tag 'book_note_empty.png' , size: '185x100', class: "edit-btn-png" %>
            <span class='destroy-btn-text'>削除する</span>
          <% end %>
        </li>
      <% elsif user_signed_in? && @request.donation != 0 && @request.people != 0 %>
        <li class="get-btn">
          <%= link_to new_request_apply_path(@request) do %>
            <%= image_tag 'book_note_empty.png' , size: '185x100', class: "get-btn-png" %>
            <span class='get-btn-text'>応募する</span>
          <% end %>
        </li>
        <li class="donation-btn">
          <%= link_to request_supports_path(@request) do %>
            <%= image_tag 'book_note_empty.png' , size: '185x100', class: "donation-btn-png" %>
            <span class='donation-btn-text'>資金援助する</span>
          <% end %>
        </li>
      <% elsif user_signed_in? && @request.donation == 0 %>
        <li class="donation-btn">
          <%= link_to new_request_apply_path(@request) do %>
            <%= image_tag 'book_note_empty.png' , size: '185x100', class: "get-btn-png" %>
            <span class='get-btn-text'>応募する</span>
          <% end %>
        </li>
      <% elsif user_signed_in? && @request.people == 0 %>
        <li class="donation-btn">
          <%= link_to request_supports_path(@request) do %>
            <%= image_tag 'book_note_empty.png' , size: '185x100', class: "donation-btn-png" %>
            <span class='donation-btn-text'>資金援助する</span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<%= render "shared/footer" %> 